name: Build & Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: windows-latest
            build_cmd: npm run build
          - os: macos-latest
            build_cmd: npm run build:mac
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 设置镜像
        run: |
          npm config set registry https://registry.npmmirror.com
          npm config set electron_mirror https://npmmirror.com/mirrors/electron/
          npm config set electron_builder_binaries_mirror https://npmmirror.com/mirrors/electron-builder-binaries/

      - name: 安装依赖
        run: |
          cd desktop
          npm install --force

      - name: 构建
        run: |
          cd desktop
          ${{ matrix.build_cmd }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
